CREATE TABLE VIDEO_GAMES 
( 
	GName VARCHAR(64) NOT NULL, 
	Price FLOAT,
	Genre VARCHAR(32),
	Description TEXT, 
	Allowed_Players INTEGER, 
	ESRB VARCHAR(4), 
	Release_Date DATE, 
	PRIMARY KEY (GName)
);

CREATE TABLE USER_ACCOUNT 
( 
	Username VARCHAR(16) NOT NULL, 
	Location VARCHAR(64), 
	Email_Address VARCHAR(64), 
	Password VARCHAR(32),
	Name VARCHAR(64), 
	Birthdate DATE,
	PRIMARY KEY (Username) 
);

CREATE TABLE RECEIVES (
	GName VARCHAR(64) NOT NULL,
	Username VARCHAR(16) NOT NULL,
	PRIMARY KEY (GName, Username),
	FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName), 
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username) 
);

CREATE TABLE REVIEWS (
	GName VARCHAR(64) NOT NULL,
	Username VARCHAR(16) NOT NULL,
	COMMENTS TEXT,
	Date DATETIME,
	Rating FLOAT,
	Hours_Played INTEGER,
	PRIMARY KEY (GName, Username),
	FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName), 
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username) 
);

CREATE TABLE USER_LIBRARY ( Lib_ID INTEGER NOT NULL, GName VARCHAR(64) NOT NULL,
Purchase_Date DATETIME,
PRIMARY KEY (Lib_ID, GName),
FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName) 
);

CREATE TABLE BELONGS_IN (
	Lib_ID INTEGER NOT NULL,
	GName VARCHAR(64) NOT NULL,
	PRIMARY KEY (Lib_ID, GName),
	FOREIGN KEY (Lib_ID) REFERENCES USER_LIBRARY (Lib_ID), 
	FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName) 
);

CREATE TABLE BUYS (
	Username VARCHAR(16) NOT NULL,
	GName VARCHAR(64) NOT NULL,
	PRIMARY KEY (Username, GName),
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username), 
	FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName)
);

CREATE TABLE WISHLIST 
( 
	Wish_ID INTEGER NOT NULL, 
	GName VARCHAR(64),
	Created_Date DATE,
	Username VARCHAR(16),
	PRIMARY KEY (Wish_ID),
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username) 
);

CREATE TABLE HOLDS 
( 
	Wish_ID INTEGER NOT NULL,
	GName VARCHAR(64) NOT NULL,
	PRIMARY KEY (Wish_ID, GName),
	FOREIGN KEY (Wish_ID) REFERENCES WISHLIST (Wish_ID), 
	FOREIGN KEY (GName) REFERENCES VIDEO_GAMES (GName) 
);

CREATE TABLE HAS (
	Wish_ID INTEGER NOT NULL,
	Username VARCHAR(16) NOT NULL,
	PRIMARY KEY (Wish_ID, Username),
	FOREIGN KEY (Wish_ID) REFERENCES WISHLIST (Wish_ID),
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username) 
);

CREATE TABLE POSSESS 
(
	Lib_ID INTEGER NOT NULL, 
	Username VARCHAR(16) NOT NULL, 
	PRIMARY KEY (Lib_ID, Username),
	FOREIGN KEY (Lib_ID) REFERENCES USER_LIBRARY(Lib_ID),
	FOREIGN KEY (Username) REFERENCES USER_ACCOUNT (Username) 
);